#!/usr/bin/sh sh

ORCA_URL="https://github.com/cee-studio/orca"

(clear)
touch config/token.h

echo -e "\n${YELLOW}[${WHITE}/${YELLOW}]${YELLOW} Checking dependencies..."
if [[ `command -v make` && `command -v gtk-launch` && `command -v zenity` && `command -v cowsay` && `command -v lolcat` ]]; then
		echo -e "${YELLOW}[${WHITE}+${YELLOW}]${YELLOW} Packages already installed."
		echo ""
else
	pkgs=(make gtk3 zenity cowsay lolcat)
	for pkg in "${pkgs[@]}"; do
		type -p "$pkg" &>/dev/null || {
			echo -e "\n${YELLOW}[${WHITE}+${YELLOW}]${WHITE} Installing package : ${ORANGE}$pkg${CYAN}"${WHITE}
			if [[ `command -v pkg` ]]; then
				pkg install "$pkg" -y
			elif [[ `command -v apt` ]]; then
				apt install "$pkg" -y
			elif [[ `command -v apt-get` ]]; then
				apt-get install "$pkg" -y
			elif [[ `command -v pacman` ]]; then
				sudo pacman -S "$pkg" --noconfirm
			elif [[ `command -v dnf` ]]; then
				sudo dnf -y install "$pkg"
			else
				echo -e "\n${RED}[${WHITE}!${RED}]${RED} Unsupported package manager, Install packages manually."
				{ reset_color; exit 1; }
			fi
		}
	done
fi

(git clone $ORCA_URL /tmp/orca)
(cd /tmp/orca && make && sudo make install)

(clear)
(cowsay "Welcome to Krokodil" 2> /dev/null | lolcat)